### ISSUE TITLE
Passing exportGlobals to modules does not work

### ISSUE THREAD

**Issue by AndrewLeedham** [flying-sheep/rollup-plugin-postcss-modules#13]
I have added a failing test in this PR: https://github.com/flying-sheep/rollup-plugin-postcss-modules/pull/14

Passing the [`exportGlobals`](https://github.com/css-modules/postcss-modules#exporting-globals) option along to postcss-modules does not seem to work, I would expect it to include global classes in the JSON object.

**Comment by AndrewLeedham** [comment]
Looks like `postcss-modules` is just out of date in rollup-plugin-postcss: with https://github.com/egoist/rollup-plugin-postcss/pull/310

**Comment by flying-sheep** [comment]
Thank you, I subscribed to that one and will wait until it’s fixed.
