### ISSUE TITLE
Update postcss to version 8

### ISSUE THREAD

**Issue by ArthurClemens** [flying-sheep/rollup-plugin-postcss-modules#15]
I got this build error:

```
[!] (plugin postcss) Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

**Comment by uribalb** [comment]
> I got this build error:
> 
> ```
> [!] (plugin postcss) Error: PostCSS plugin autoprefixer requires PostCSS 8.
> Migration guide for end-users:
> https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
> ```

@ArthurClemens  wrong repo 😉

**Comment by ArthurClemens** [comment]
O, I'm sorry. Thanks for the heads up.

**Comment by manuelbieh** [comment]
To bring this issue back to life with a little bit more ontopic question: is there any chance to update this plugin to work with PostCSS 8? I'm using it in my rollup build and I'm super happy with it so far, but it holds me back from upgrading the rest of my PostCSS setup to PostCSS 8
