### ISSUE TITLE
Update rollup-plugin-postcss dependency

### ISSUE THREAD

**Issue by skylarmb** [flying-sheep/rollup-plugin-postcss-modules#16]
https://github.com/egoist/rollup-plugin-postcss/releases/tag/v4.0.0

v4.0 was released with postcss 8.0 as well as a bug [fix](https://github.com/egoist/rollup-plugin-postcss/commit/6480f02681d1526c102f3e99891b788d01031f32#diff-76dddaa2670bb7751a24aa89da23d2a3f5e900dd04bd153faecc05fa370e8938R211) that fixed the `inject` option being ignored.

**Comment by flying-sheep** [comment]
Fixed in #17
