### ISSUE TITLE
Extracted "*.map.css" file doesn't contain hierarchy of folders for the "sources".

### ISSUE THREAD

**Issue by siarheiyelin** [flying-sheep/rollup-plugin-postcss-modules#30]
Extracted "*.map.css" file doesn't contain hierarchy of folders for the "sources".

At current moment, this library internally uses "rollup-plugin-postcss" as a dependency. And therefore it inherits the following issue related to extracted source maps: https://github.com/egoist/rollup-plugin-postcss/issues/441

I wonder, is it possible to apply some workaround to fix this issue somehow?

Actual result:
```{"version":3,"sources":["test.scss"]...```
Expected result:
```{"version":3,"sources":["../src/nestedFolder1/nestedFolder2/test.scss"]...```

**Comment by siarheiyelin** [comment]
Okay, it seems I've just found a workaround for this - it's necessary to pass "to" attribute via options, e.g.:
//
rollupPluginPostCssModules({ sourceMap: true, modules: true, extract: "styles.css", **to: path.resolve("./build/styles.css")** })
//
As a result the source location looks like this:
```
{"version":3,"sources":["../src/nestedFolder1/nestedFolder2/test.scss"],
```

Probably it makes sense to set it automatically. At least, the "postcss" docs mention, that it's usually set automatically by runners. https://github.com/postcss/postcss.

**Comment by flying-sheep** [comment]
I’m passing on most options to https://github.com/egoist/rollup-plugin-postcss, so I think you should post this feature request there. I’m going to close this, but if you have a good reason why it’s supposed to be implemented here instead, I’ll happily reopen!
