### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by DongShelton** [flying-sheep/rollup-plugin-postcss-modules#5]
I am using this plugin,:
```javascript
    postcss({
      inject: false,
      extract: true,
      modules: true,
      minimize: true,
      writeDefinitions: true,
      plugins: [
        require('precss')(),
        require('autoprefixer')(),
      ],
    }),
    typescript(),
```
And I import css file in .tsx file:
```typescript
import styles from './style.css';
```
But it will yells me: Cannot find module style.css

**Comment by flying-sheep** [comment]
please create a minimal example project (e.g. on https://gist.github.com) where i can reproduce this.

**Comment by DongShelton** [comment]
Thank you for the response, it looks like that my tsconfig is incorrect, I have already solved this problem

**Comment by flying-sheep** [comment]
That’s great!
