### ISSUE TITLE
1.0.9 causes existing rollup configs to fail

### ISSUE THREAD

**Issue by chrisvxd** [flying-sheep/rollup-plugin-postcss-modules#6]
Thanks for the awesome work!

## What I did

Generated a new project with [create-react-library](https://github.com/transitive-bullshit/create-react-library), which installed v1.0.9 of this package.

## What I expected

The generated project to build correctly with rollup after installing, as it did with `v1.0.8`.

## What happened

I received the error when building with rollup

```
[!] Error: 'rollup-plugin-postcss-modules' provides a 'postcss-modules' plugin and its `getJSON()`. You cannot specify `modules.getJSON`
```

I tracked it down to this config in the generated `rollup.config.js`.

```
    postcss({
      modules: true,
      writeDefinitions: true
    }),
```

It looks like `v1.0.9` of this plugin includes a breaking change which results in this.

To fix, can I suggest:

* Rolling back / making the change backwards compatible and releasing `v1.0.10` so external dependants can seamlessly upgrade
* Releasing the breaking changes as `v2.0.0` so people have to explicitly bump their libs.
* Uploading the latest published code to Github so we can see what's going on :)

**Comment by flying-sheep** [comment]
fixed in abe6f54b70a4f3bf1cbb72edcd256902ed2a87f1, but create-react-library since switched to rollup-plugin-postcss anyway :cry:

mine has typescript support though, so the author might want to reconsider
